[[language]]
name = "rust"
auto-format = false

[[language]]
name = "c"
scope = "source.c"
file-types = ["c", "h"]
auto-format = false
language-servers = ["clangd"]

[indent]
unit = "2"
tab-width = "2"

[language-server.clangd]
command = "clangd"
args = ["--query-driver=/usr/bin/arm-none-eabi-*"]
